[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "v1.3.0"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "v0.9.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "v1.3.0"

[prune]
  non-go = true
  go-tests = true
  unused-packages = true
